title: Windows Live Essentials (Archive)
description: This is an archive of the original final release of Windows Live Essentials 2012 in April 2014. It is 100% unmodified and authentic.
theme: jekyll-theme-cayman
